# Generated by Django 5.0.6 on 2024-06-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', 'create_permissions_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='favorite_dish',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='find_me',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='loves',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='second_favorite_website',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='why_read',
        ),
    ]
