# Generated by Django 5.0.6 on 2024-06-06 10:12

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_personalsocial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=15, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
    ]
