# Generated by Django 5.0.6 on 2024-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='personalprofile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='bio',
            field=models.CharField(blank=True, help_text='A short description about yourself', max_length=200, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='country',
            field=models.CharField(blank=True, help_text='Your country', max_length=200, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='hometown',
            field=models.CharField(blank=True, help_text='Your hometown', max_length=30, null=True, verbose_name='Hometown'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='primary_language',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Primary language'),
        ),
    ]
