# Generated by Django 5.0.6 on 2024-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_personalprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
