# Generated by Django 5.0.6 on 2024-06-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_personalprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('TZ', 'Tanzania'), ('KE', 'Kenya'), ('RW', 'Rwanda'), ('BI', 'Burundi'), ('ZA', 'South Africa'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('EG', 'Egypt'), ('MA', 'Morocco'), ('ML', 'Mali'), ('CI', 'Ivory Coast'), ('MZ', 'Mozambique'), ('ER', 'Eritrea'), ('SD', 'Sudan'), ('ET', 'Ethiopia'), ('SO', 'Somalia')], help_text='Your country', max_length=200, null=True, verbose_name='Country'),
        ),
    ]
