# Generated by Django 5.0.6 on 2024-06-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_personalprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pictures/<django.db.models.fields.related.OneToOneField>', verbose_name='Profile picture'),
        ),
    ]
