# Generated by Django 5.0.6 on 2024-06-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_personalprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='gender',
        ),
    ]
