# Generated by Django 5.0.6 on 2024-06-24 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_favorite'),
        ('business', '0002_rename_date_posted_businessreview_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='business.businessprofile')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.personalaccount')),
            ],
            options={
                'unique_together': {('personal', 'business')},
            },
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
