# Generated by Django 5.0.6 on 2024-06-25 10:41

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_favoritebusiness_business'),
        ('business', '0002_rename_date_posted_businessreview_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-', editable=False, length=18, max_length=40, prefix='', primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(blank=True, help_text='Name of the collection', max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of the collection', null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('public', models.BooleanField(default=True, help_text='Public or private collection', verbose_name='Public')),
                ('businesses', models.ManyToManyField(blank=True, related_name='collections', to='business.businessprofile')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='accounts.personalaccount')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'indexes': [models.Index(fields=['slug'], name='accounts_co_slug_33622a_idx'), models.Index(fields=['id'], name='accounts_co_id_d13569_idx')],
            },
        ),
    ]
