# Generated by Django 5.0.6 on 2024-07-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='reputation',
            field=models.BigIntegerField(default=0),
        ),
    ]
