# Generated by Django 5.0.6 on 2024-06-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_personalprofile_gender'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessreview',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='businessreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businessreview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Rate the business from 1 to 5 stars.'),
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='business.businessreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='accounts.personalaccount')),
            ],
            options={
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.DeleteModel(
            name='ReviewThumbsUp',
        ),
    ]
