# Generated by Django 5.0.6 on 2024-06-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_collection_user'),
        ('business', '0002_rename_date_posted_businessreview_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('helpful', 'Helpful'), ('appriciate', 'Appriciate'), ('LIKE', 'like')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='business.businessreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='accounts.personalaccount')),
            ],
            options={
                'unique_together': {('user', 'review')},
            },
        ),
        migrations.DeleteModel(
            name='ReviewVote',
        ),
    ]
