# Generated by Django 5.0.6 on 2024-06-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_reviewreaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rate the business from 1 to 5 stars.'),
        ),
    ]
