# Generated by Django 5.0.6 on 2024-06-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_businessreview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessreview',
            options={'ordering': ('-created_at',)},
        ),
    ]
