# Generated by Django 5.0.6 on 2024-07-01 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_reviewhelpful_delete_reviewreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
