# Generated by Django 5.0.6 on 2024-07-01 09:42

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_businessreview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreview',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-', editable=False, length=32, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
    ]
