# Generated by Django 5.0.6 on 2024-07-05 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_collection_user'),
        ('business', '0009_alter_businessreview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewhelpful',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='business.businessreview'),
        ),
        migrations.AlterField(
            model_name='reviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='accounts.personalaccount'),
        ),
    ]
