# Generated by Django 5.0.6 on 2024-07-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_businessservices_businesssubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessContact',
        ),
    ]
