# Generated by Django 5.0.6 on 2024-07-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_businesscontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessShortMessage',
        ),
    ]
